### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by munichpavel** [RasaHQ/pokedex-demo#1]
This looks like a fun project. Could you please add a license? Is it also Apache 2.0? I like the cute tiger cub picture.

**Comment by koaning** [comment]
I've added GNU 3 for now, I'll need to check internally at Rasa to confirm this is appropriate. Once confirmed I'll reply here and close the issue.

**Comment by koaning** [comment]
We've settled on Apache 2. Updating repo now.
