### ISSUE TITLE
Replacing pokenames.txt for a richer dataset

### ISSUE THREAD

**Issue by juandes** [RasaHQ/pokedex-demo#5]
Currently, the only data available in the project is the pokenames.txt file, which holds the names of Pokemon. However, I propose to replace it (or adding) another file that contains the Pokemon names, plus other information such as its Pokedex number, type, evolution, and more. That way, the bot could answer more in-depth questions about the Pokemon.

**Example** 
Suppose, you want to know Pikachu's name:

```
User> What's Pikachu's number?
Bot> Pikachu is Pokemon # 25.
```

**Comment by koaning** [comment]
we can add a json blob with info, but the text fills a purpose for recognizing entities at the moment. i have the blob from kaggle too, or do did you have another dataset in mind?

**Comment by juandes** [comment]
Not a particular one. The one from Kaggle should do the job :D

**Comment by koaning** [comment]
There's an experimental feature within Rasa called the "knowledge base" that might allow us to automatically map the json to something that is query-able. Until then I'd be interested in keeping it simple such that when you give it a name it retreives for you the photo and the pokedex text.

**Comment by juandes** [comment]
Just to make sure we're talking about the same thing, is this the dataset?
https://www.kaggle.com/rajgaurav9/pokemon-stats-and-description-with-pictures-json

**Comment by koaning** [comment]
Yes. Althought I might want to host the images online somewhere, it might bloat the git repo otherwise. With Rasa you can easily pass the url of the image in order for it to show up in the chat.

**Comment by juandes** [comment]
This issue is related to PR #7 and #9 so, should we close it?

**Comment by koaning** [comment]
Agreed.
